### ISSUE TITLE
TLS Errors and Excessive logging - Helm Chart 1.6 - Operator Controller Manager

### ISSUE THREAD

**Issue by stand-sure** [kubeshop/testkube#2467]
**Describe the bug**

The bug in https://github.com/kubeshop/testkube/issues/2231 is not fixed in the most recent Helm Chart (testkube-1.6.0)

**To Reproduce**
1. Delete the previous install
2. Run either `testkube init` or `helm install`
3. Add a test
4. Inspect the logs for the `manager` container in the `testkube-operator-controller-manager-...`
5.  Observe 4-5 log messages per second `...http: TLS handshake error from 10.42.213.64:52162: remote error: tls: bad certificate`

**Expected behavior**
The certificate should be valid. The addition of a test should not cause thousands of errors to be logged even if the cert is not valid.

**Version / Cluster**
- Which testkube version? 
```shell
Client Version 1.5.41
Server Version v1.6.0
Commit 192e00e10fa9ae710c2d1f72ad2c328acc64faf2
Built by goreleaser
Build date 2022-09-30T08:15:11Z
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  - RKE1
  - k3s
- What Kubernetes version?
  - Happens on multiple k8s bersions
    - Server Version: v1.22.11 
    - Server Version: v1.23.2+k3s1

**Comment by vsukhin** [comment]
Thank you @stand-sure We will check it out

**Comment by dejanzele** [comment]
@stand-sure can you please do `kubectl get pods --all-namespaces -o wide | grep 10.42.213.64` and post which pod is calling the Operator?
Or if there are different IP addresses, can you please use the above command and post which pods are calling it?

**Comment by stand-sure** [comment]
I tore that one down -- let me pull from the other install

**Comment by dejanzele** [comment]
@stand-sure can you identify to which pod does the IP 10.42.213.64 belongs?

Are you by any chance using Konnectivity or Prometheus Operator?

**Comment by stand-sure** [comment]
Prometheus in one environment but not both

**Comment by stand-sure** [comment]
on my local (rancher desktop)

```shell
kubectl --namespace testkube logs testkube-operator-controller-manager-6498d9b577-qxwj6 --follow --all-containers
...
2022/10/05 14:03:50 http: TLS handshake error from 10.42.0.1:37178: remote error: tls: bad certificate

kubectl get pods --output wide --all-namespaces | grep 10.42.0.1
velero          minio-setup-mw5h8                                                 0/1     Completed          0               7d16h   10.42.0.184   anderson10   <none>           <none>
```

I'll re-run on the RKE1 one

**Comment by stand-sure** [comment]
no luck on resolving the one in RKE

![image](https://user-images.githubusercontent.com/11789693/194087975-fd865b93-7ec3-4ea1-8a7a-3db33a0d142b.png)

**Comment by haimprecise** [comment]
Trying to identify the pod on EKS, no luck as well.

**Comment by dejanzele** [comment]
This is fixed with the following [PR](https://github.com/kubeshop/helm-charts/pull/298).

`testkube@1.6.39` does not have the spam TLS handshake error.

**Comment by haimprecise** [comment]
Updated to testkube@1.6.41.
I am using the Helm Chart along with Argo CD.
I have synced (with Force + Prune + Replace) the deployments successfully and have the latest images installed.
However, still see those bad certificate errors.
any steps I need to do?
